version: "3.7"

services: 
    db:
        image: postgres
        restart: "always"
        environment: 
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_DATABASE}
        volumes: 
            - ./.pgdata:/var/lib/postgresql/data
        ports: 
            - 5433:5432
    api:
        build: .
        environment: 
            DATABASE_URL: ${DB_URL}
        container_name: api
        depends_on: 
            - db
        ports: 
            - ${PORT}:${PORT}
        volumes: 
            - .:/usr/app
        working_dir: /usr/app
        command: yarn run dev
        logging: 
            driver: "json-file"
            options: 
                max-size: "10m"
                max-file: "5"